name: release
on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/github-issue-prompter

    permissions:
      id-token: write

    steps:

      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python...
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: 3. Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: 4. Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
